name: Hotel-App End-to-End Tests

on:
  workflow_dispatch:
    schedule:
      - cron: "0 9 * * 1"
  push:
    branches: [main]
    paths:
      - "benchmarks/hotel-app/**"
      - "utils/**"
      - "tools/**"
      - "runner/**"

  pull_request:
    branches: [main]
    paths:
      - "benchmarks/hotel-app/**"
      - "utils/**"
      - "tools/**"
      - "runner/**"

env:
  GOOS: linux
  GO111MODULE: on
  PORT: 50051
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    name: Build and push all images
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            geo, profile, rate, recommendation, reservation, user, search,
          ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: "true"

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        env:
            GOPRIVATE_KEY: ${{ secrets.XDT_REPO_ACCESS_KEY }}
        uses: docker/build-push-action@v3
        with:
          push: true
          file: benchmarks/hotel-app/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          target: ${{ matrix.target }}
          tags: vhiveease/hotel-app-${{ matrix.service }}:latest
          build-args: SERVICE=${{ matrix.service }}
          context: .



  test-compose:
    name: Test Docker Compose
    needs: build-and-push
    env:
      YAML_DIR: benchmarks/hotel-app/yamls/docker-compose/
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            geo,
            geo-tracing,
            profile,
            rate,
            recommendation,
            reservation,
            user,
            search,
            search-tracing,
          ]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: "true"

      - name: start docker-compose benchmark
        run: |
          docker-compose -f ${{ env.YAML_DIR }}/dc-${{ matrix.service }}.yaml pull
          docker-compose -f ${{ env.YAML_DIR }}/dc-${{ matrix.service }}.yaml up &> log_file &
          sleep 60s
          cat log_file

      - name: invoke the chain
        run: |
          ./tools/bin/grpcurl -plaintext localhost:50000 helloworld.Greeter.SayHello

      - name: show docker-compose log
        run: cat log_file

  test-knative:
    name: Test Knative Deployment
    needs: build-and-push
    env:
      KIND_VERSION: v0.14.0
      K8S_VERSION: v1.23
      YAML_DIR: benchmarks/hotel-app/yamls/knative/

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: hotel-app-geo
            file: kn-geo.yaml
          - service: hotel-app-geo-tracing
            file: kn-geo-tracing.yaml
          - service: hotel-app-profile
            file: kn-profile.yaml
          - service: hotel-app-rate
            file: kn-rate.yaml
          - service: hotel-app-recommendation
            file: kn-recommendation.yaml
          - service: hotel-app-reservation
            file: kn-reservation.yaml
          - service: hotel-app-user
            file: kn-user.yaml
          - service: hotel-app-search
            file: kn-search.yaml
          - service: hotel-app-search-tracing
            file: kn-search-tracing.yaml
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Checkout LFS objects
        run: git lfs checkout

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      ## Setup a Knative cluster to test the service
      - name: Create k8s Kind Cluster
        run: bash ./runner/scripts/01-kind.sh

      - name: Install Serving
        run: bash ./runner/scripts/02-serving.sh

      - name: Install Kourier
        run: bash ./runner/scripts/02-kourier.sh

      - name: Setup domain
        run: |
          INGRESS_HOST="127.0.0.1"
          KNATIVE_DOMAIN=$INGRESS_HOST.sslip.io
          kubectl patch configmap -n knative-serving config-domain -p "{\"data\": {\"$KNATIVE_DOMAIN\": \"\"}}"


      ## Test the service
      - name: Deploy database and memcached
        working-directory: benchmarks/hotel-app/yamls/knative/
        run: |
          kubectl apply -f database.yaml
          kubectl apply -f memcached.yaml

      - name: Deploy knative
        run: |
          kubectl apply -f ${{ env.YAML_DIR }}/${{ matrix.file }}

      - name: Check if service is ready
        run: |
          kubectl wait --for=condition=Ready -f ${{ env.YAML_DIR }}/${{ matrix.file }} --timeout 120s
          kubectl get service
          kubectl get -f ${{ env.YAML_DIR }}/${{ matrix.file }}

      - name: Test invoking once
        working-directory: tools/test-client
        run: |
          set -x
          go build ./test-client.go

          NODEPORT=80
          url=$(kubectl get kservice ${{ matrix.service }} | awk '$2 ~ /http/ {sub(/http\:\/\//,""); print $2}')

          ./test-client --addr $url:$NODEPORT --name "Example text for CI"


      - name: Print logs
        if: ${{ always() }}
        run: |
          set -x

          pod_list=$(kubectl get pods -n default -o jsonpath="{.items[*].name}")
          for pod in $pod_list
          do
            kubectl logs $pod
          done

      - name: Print logs from database and mmc
        if: ${{ always() }}
        run: |
          set -x
          kubectl logs deployment/hotel-app-database
          kubectl logs deployment/hotel-app-mmc

      - name: Down
        if: ${{ always() }}
        run: |
          kubectl delete -f ${{ env.YAML_DIR }}/${{ matrix.file }} --namespace default --wait
          kubectl delete -f ${{ env.YAML_DIR }}/database.yaml
          kubectl delete -f ${{ env.YAML_DIR }}/memcached.yaml
